FROM php:8.3-fpm-alpine as laravel
WORKDIR /var/www/html
COPY . .

# Manual symlink instead of php artisan storage:link
RUN ln -s /var/www/html/storage/app/public /var/www/html/public/storage

FROM nginx:alpine
COPY --from=laravel /var/www/html/public /var/www/html/public
